version: "3.4"

services:
    api:
        build:
          context: ./bike-webapi
          dockerfile: Dockerfile
        ports:
          - "5000:80"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"

    ui:
      build:
        context: ./bike-ui
        dockerfile: Dockerfile
      ports:
        - 5173:5173
      depends_on:
        - api